#!/usr/bin/env python3
"""
Setup script for simulated multi-camera RTSP streams using mediamtx.
Downloads test footage and starts mediamtx with 3 camera streams.
"""
import os
import sys
import subprocess
import time
import urllib.request
from pathlib import Path


# Test video URLs (sample footage - replace with actual test videos)
TEST_VIDEOS = {
    "cam1.mp4": "https://github.com/intel-iot-devkit/sample-videos/raw/master/person-bicycle-car-detection.mp4",
    "cam2.mp4": "https://github.com/intel-iot-devkit/sample-videos/raw/master/one-by-one-person-detection.mp4",
    "cam3.mp4": "https://github.com/intel-iot-devkit/sample-videos/raw/master/person-bicycle-car-detection.mp4",
}


def download_test_footage(footage_dir: Path):
    """Download test footage if not present."""
    footage_dir.mkdir(parents=True, exist_ok=True)

    for filename, url in TEST_VIDEOS.items():
        filepath = footage_dir / filename
        if filepath.exists():
            print(f"✓ {filename} already exists")
            continue

        print(f"Downloading {filename}...")
        try:
            urllib.request.urlretrieve(url, filepath)
            print(f"✓ Downloaded {filename}")
        except Exception as e:
            print(f"✗ Failed to download {filename}: {e}")
            # Create a dummy file for testing
            create_dummy_video(filepath)


def create_dummy_video(filepath: Path):
    """Create a dummy video file using ffmpeg for testing."""
    print(f"Creating dummy video at {filepath}...")
    try:
        subprocess.run([
            "ffmpeg", "-f", "lavfi", "-i", "testsrc=duration=30:size=640x480:rate=30",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-y", str(filepath)
        ], check=True, capture_output=True)
        print(f"✓ Created dummy video {filepath.name}")
    except (subprocess.CalledProcessError, FileNotFoundError):
        print(f"✗ Could not create dummy video (ffmpeg not available)")
        # Create empty file as last resort
        filepath.write_bytes(b"")


def generate_mediamtx_config(footage_dir: Path, config_path: Path):
    """Generate mediamtx.yml configuration."""
    config = f"""# MediaMTX configuration for simulated multi-camera RTSP streams
# Generated by setup_simulated_cameras.py

paths:
  cam1:
    source: publisher
    sourceOnDemand: false
    runOnDemand: ffmpeg -re -stream_loop -1 -i {footage_dir}/cam1.mp4 -c copy -f rtsp rtsp://localhost:8554/cam1
    runOnDemandRestart: true

  cam2:
    source: publisher
    sourceOnDemand: false
    runOnDemand: ffmpeg -re -stream_loop -1 -i {footage_dir}/cam2.mp4 -c copy -f rtsp rtsp://localhost:8554/cam2
    runOnDemandRestart: true

  cam3:
    source: publisher
    sourceOnDemand: false
    runOnDemand: ffmpeg -re -stream_loop -1 -i {footage_dir}/cam3.mp4 -c copy -f rtsp rtsp://localhost:8554/cam3
    runOnDemandRestart: true

api:
  address: :9997

metrics:
  address: :9998

logLevel: info
logFormat: json
"""
    config_path.write_text(config)
    print(f"✓ Generated mediamtx config at {config_path}")


def start_mediamtx(config_path: Path):
    """Start mediamtx container."""
    print("Starting mediamtx container...")
    try:
        subprocess.run([
            "docker", "run", "-d",
            "--name", "ibvap_mediamtx",
            "-p", "8554:8554",
            "-p", "1935:1935",
            "-p", "8888:8888",
            "-v", f"{config_path}:/mediamtx.yml",
            "-v", f"{footage_dir}:/footage",
            "bluenviron/mediamtx:latest",
            "/mediamtx.yml"
        ], check=True)
        print("✓ mediamtx container started")
        return True
    except subprocess.CalledProcessError as e:
        print(f"✗ Failed to start mediamtx: {e}")
        return False


def wait_for_streams(timeout: int = 30):
    """Wait for RTSP streams to be available."""
    print("Waiting for RTSP streams to be ready...")
    import socket

    start = time.time()
    while time.time() - start < timeout:
        try:
            sock = socket.create_connection(("localhost", 8554), timeout=2)
            sock.close()
            print("✓ RTSP port 8554 is accessible")
            return True
        except (ConnectionRefusedError, socket.timeout):
            time.sleep(1)

    print("✗ Timeout waiting for RTSP streams")
    return False


def verify_streams():
    """Verify all 3 camera streams are accessible."""
    print("Verifying camera streams...")
    streams = ["cam1", "cam2", "cam3"]
    all_ok = True

    for stream in streams:
        url = f"rtsp://localhost:8554/{stream}"
        try:
            # Quick ffprobe check
            result = subprocess.run([
                "ffprobe", "-v", "error", "-select_streams", "v:0",
                "-show_entries", "stream=width,height", "-of", "csv=p=0", url
            ], capture_output=True, timeout=10)
            if result.returncode == 0:
                print(f"✓ {stream}: {result.stdout.decode().strip()}")
            else:
                print(f"✗ {stream}: ffprobe failed")
                all_ok = False
        except (subprocess.TimeoutExpired, FileNotFoundError):
            print(f"? {stream}: ffprobe not available, assuming OK")
        except Exception as e:
            print(f"✗ {stream}: {e}")
            all_ok = False

    return all_ok


def main():
    project_root = Path(__file__).parent.parent
    footage_dir = project_root / "footage"
    config_path = project_root / "mediamtx.yml"

    print("=" * 60)
    print("IBVAP Phase 0: Simulated Camera Setup")
    print("=" * 60)

    # Download test footage
    download_test_footage(footage_dir)

    # Generate mediamtx config
    generate_mediamtx_config(footage_dir, config_path)

    # Check if mediamtx is already running
    result = subprocess.run(["docker", "ps", "-q", "-f", "name=ibvap_mediamtx"], capture_output=True, text=True)
    if result.stdout.strip():
        print("mediamtx already running, restarting...")
        subprocess.run(["docker", "stop", "ibvap_mediamtx"], capture_output=True)
        subprocess.run(["docker", "rm", "ibvap_mediamtx"], capture_output=True)

    # Start mediamtx
    if not start_mediamtx(config_path):
        sys.exit(1)

    # Wait for streams
    if not wait_for_streams():
        print("Streams may not be fully ready yet. Check docker logs.")
        sys.exit(1)

    # Verify streams
    if verify_streams():
        print("\n" + "=" * 60)
        print("✓ All 3 simulated camera streams are running!")
        print("=" * 60)
        print("RTSP URLs:")
        print("  cam1: rtsp://localhost:8554/cam1")
        print("  cam2: rtsp://localhost:8554/cam2")
        print("  cam3: rtsp://localhost:8554/cam3")
        print("\nMediaMTX API: http://localhost:9997")
        print("MediaMTX Metrics: http://localhost:9998")
    else:
        print("\n⚠ Some streams may have issues. Check docker logs:")
        print("  docker logs ibvap_mediamtx")


if __name__ == "__main__":
    main()